LOCAL_PATH := $(call my-dir)/bullet-2.82-r2704/src

include $(CLEAR_VARS)

LOCAL_MODULE    := bullet

LOCAL_EXPORT_C_INCLUDES := \
$(LOCAL_PATH) \
$(LOCAL_PATH)/BulletCollision/BroadphaseCollision \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch \
$(LOCAL_PATH)/BulletCollision/CollisionShapes \
$(LOCAL_PATH)/BulletCollision/Gimpact \
$(LOCAL_PATH)/BulletCollision/NarrowPhaseCollision \
$(LOCAL_PATH)/BulletDynamics/Character \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver \
$(LOCAL_PATH)/BulletDynamics/Dynamics \
$(LOCAL_PATH)/BulletDynamics/Featherstone \
$(LOCAL_PATH)/BulletDynamics/MLCPSolvers \
$(LOCAL_PATH)/BulletDynamics/Vehicle \
$(LOCAL_PATH)/BulletSoftBody \
$(LOCAL_PATH)/LinearMath \

LOCAL_CFLAGS := $(LOCAL_C_INCLUDES:%=-I%)

LOCAL_SRC_FILES := \
$(LOCAL_PATH)/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp \
$(LOCAL_PATH)/BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp \
$(LOCAL_PATH)/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/BroadphaseCollision/btDbvt.cpp \
$(LOCAL_PATH)/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp \
$(LOCAL_PATH)/BulletCollision/BroadphaseCollision/btDispatcher.cpp \
$(LOCAL_PATH)/BulletCollision/BroadphaseCollision/btMultiSapBroadphase.cpp \
$(LOCAL_PATH)/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp \
$(LOCAL_PATH)/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp \
$(LOCAL_PATH)/BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btCollisionObject.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btCollisionWorld.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btGhostObject.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btHashedSimplePairCache.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btManifoldResult.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/btUnionFind.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btBox2dShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btBoxShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btCapsuleShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btCollisionShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btCompoundShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btConcaveShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btConeShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btConvex2dShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btConvexHullShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btConvexInternalShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btConvexPolyhedron.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btConvexShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btCylinderShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btEmptyShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btMultiSphereShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btOptimizedBvh.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btShapeHull.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btSphereShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btStaticPlaneShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btStridingMeshInterface.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btTetrahedronShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btTriangleBuffer.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btTriangleCallback.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btTriangleMesh.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btTriangleMeshShape.cpp \
$(LOCAL_PATH)/BulletCollision/CollisionShapes/btUniformScalingShape.cpp \
$(LOCAL_PATH)/BulletCollision/Gimpact/btContactProcessing.cpp \
$(LOCAL_PATH)/BulletCollision/Gimpact/btGenericPoolAllocator.cpp \
$(LOCAL_PATH)/BulletCollision/Gimpact/btGImpactBvh.cpp \
$(LOCAL_PATH)/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletCollision/Gimpact/btGImpactQuantizedBvh.cpp \
$(LOCAL_PATH)/BulletCollision/Gimpact/btGImpactShape.cpp \
$(LOCAL_PATH)/BulletCollision/Gimpact/btTriangleShapeEx.cpp \
$(LOCAL_PATH)/BulletCollision/Gimpact/gim_box_set.cpp \
$(LOCAL_PATH)/BulletCollision/Gimpact/gim_contact.cpp \
$(LOCAL_PATH)/BulletCollision/Gimpact/gim_memory.cpp \
$(LOCAL_PATH)/BulletCollision/Gimpact/gim_tri_collision.cpp \
$(LOCAL_PATH)/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp \
$(LOCAL_PATH)/BulletCollision/NarrowPhaseCollision/btConvexCast.cpp \
$(LOCAL_PATH)/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp \
$(LOCAL_PATH)/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp \
$(LOCAL_PATH)/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp \
$(LOCAL_PATH)/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp \
$(LOCAL_PATH)/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp \
$(LOCAL_PATH)/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp \
$(LOCAL_PATH)/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp \
$(LOCAL_PATH)/BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp \
$(LOCAL_PATH)/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp \
$(LOCAL_PATH)/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp \
$(LOCAL_PATH)/BulletDynamics/Character/btKinematicCharacterController.cpp \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver/btContactConstraint.cpp \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver/btFixedConstraint.cpp \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver/btGearConstraint.cpp \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver/btHinge2Constraint.cpp \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver/btHingeConstraint.cpp \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.cpp \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver/btSliderConstraint.cpp \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.cpp \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver/btTypedConstraint.cpp \
$(LOCAL_PATH)/BulletDynamics/ConstraintSolver/btUniversalConstraint.cpp \
$(LOCAL_PATH)/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp \
$(LOCAL_PATH)/BulletDynamics/Dynamics/btRigidBody.cpp \
$(LOCAL_PATH)/BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp \
$(LOCAL_PATH)/BulletDynamics/Featherstone/btMultiBody.cpp \
$(LOCAL_PATH)/BulletDynamics/Featherstone/btMultiBodyConstraint.cpp \
$(LOCAL_PATH)/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.cpp \
$(LOCAL_PATH)/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.cpp \
$(LOCAL_PATH)/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.cpp \
$(LOCAL_PATH)/BulletDynamics/Featherstone/btMultiBodyJointMotor.cpp \
$(LOCAL_PATH)/BulletDynamics/Featherstone/btMultiBodyPoint2Point.cpp \
$(LOCAL_PATH)/BulletDynamics/MLCPSolvers/btDantzigLCP.cpp \
$(LOCAL_PATH)/BulletDynamics/MLCPSolvers/btMLCPSolver.cpp \
$(LOCAL_PATH)/BulletDynamics/Vehicle/btRaycastVehicle.cpp \
$(LOCAL_PATH)/BulletDynamics/Vehicle/btWheelInfo.cpp \
$(LOCAL_PATH)/BulletSoftBody/btDefaultSoftBodySolver.cpp \
$(LOCAL_PATH)/BulletSoftBody/btSoftBody.cpp \
$(LOCAL_PATH)/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletSoftBody/btSoftBodyHelpers.cpp \
$(LOCAL_PATH)/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.cpp \
$(LOCAL_PATH)/BulletSoftBody/btSoftRigidCollisionAlgorithm.cpp \
$(LOCAL_PATH)/BulletSoftBody/btSoftRigidDynamicsWorld.cpp \
$(LOCAL_PATH)/BulletSoftBody/btSoftSoftCollisionAlgorithm.cpp \
$(LOCAL_PATH)/LinearMath/btAlignedAllocator.cpp \
$(LOCAL_PATH)/LinearMath/btConvexHull.cpp \
$(LOCAL_PATH)/LinearMath/btConvexHullComputer.cpp \
$(LOCAL_PATH)/LinearMath/btGeometryUtil.cpp \
$(LOCAL_PATH)/LinearMath/btPolarDecomposition.cpp \
$(LOCAL_PATH)/LinearMath/btQuickprof.cpp \
$(LOCAL_PATH)/LinearMath/btSerializer.cpp \
$(LOCAL_PATH)/LinearMath/btVector3.cpp \

include $(BUILD_STATIC_LIBRARY)
