all:
	mkdir -p ../../GameEngine/dev/inc
	mkdir -p ../../GameEngine/dev/libs
	mkdir -p ../../GameEngine/dev/libs/.objs
	mkdir -p ../../GameEngine/dev/libs/Android
	mkdir -p ../../GameEngine/dev/libs/Android/.objs
	mkdir -p ../../GameEngine/dev/libs/Android\ TV
	mkdir -p ../../GameEngine/dev/libs/Android\ TV/.objs
	mkdir -p ../../GameEngine/dev/libs/iOS
	mkdir -p ../../GameEngine/dev/libs/iOS/.objs
	mkdir -p ../../GameEngine/dev/libs/Linux
	mkdir -p ../../GameEngine/dev/libs/Linux/.objs
	mkdir -p ../../GameEngine/dev/libs/MacOS
	mkdir -p ../../GameEngine/dev/libs/MacOS/.objs
	mkdir -p ../../GameEngine/dev/libs/Samsung\ SMART\ TV
	mkdir -p ../../GameEngine/dev/libs/Samsung\ SMART\ TV/.objs
	mkdir -p ../../GameEngine/dev/libs/Tizen
	mkdir -p ../../GameEngine/dev/libs/Tizen/.objs
	mkdir -p ../../GameEngine/dev/libs/tvOS
	mkdir -p ../../GameEngine/dev/libs/tvOS/.objs
	mkdir -p ../../GameEngine/dev/libs/WebGL
	mkdir -p ../../GameEngine/dev/libs/WebGL/.objs
	mkdir -p ../../GameEngine/dev/libs/Windows
	mkdir -p ../../GameEngine/dev/libs/Windows/.objs
	mkdir -p ../../GameEngine/dev/libs/Windows\ Phone
	mkdir -p ../../GameEngine/dev/libs/Windows\ Phone/.objs


	$(MAKE) -C Android
	$(MAKE) -C Android\ TV
	$(MAKE) -C iOS
	$(MAKE) -C Linux
	$(MAKE) -C MacOS
	$(MAKE) -C Samsung\ SMART\ TV
	$(MAKE) -C Tizen
	$(MAKE) -C tvOS
	$(MAKE) -C WebGL
	$(MAKE) -C Windows
	$(MAKE) -C Windows\ Phone
