all:
	mkdir -p ../../../GameEngine/bin/lua/Android
	mkdir -p ../../../GameEngine/bin/lua/Android\ TV
	mkdir -p ../../../GameEngine/bin/lua/iOS
	mkdir -p ../../../GameEngine/bin/lua/Linux
	mkdir -p ../../../GameEngine/bin/lua/MacOS
	mkdir -p ../../../GameEngine/bin/lua/Samsung\ SMART\ TV
	mkdir -p ../../../GameEngine/bin/lua/Tizen
	mkdir -p ../../../GameEngine/bin/lua/tvOS
	mkdir -p ../../../GameEngine/bin/lua/WebGL
	mkdir -p ../../../GameEngine/bin/lua/Windows
	mkdir -p ../../../GameEngine/bin/lua/Windows\ Phone
	$(MAKE) -C Android
	$(MAKE) -C Android\ TV
	$(MAKE) -C iOS
	$(MAKE) -C Linux
	$(MAKE) -C MacOS
	$(MAKE) -C Samsung\ SMART\ TV
	$(MAKE) -C Tizen
	$(MAKE) -C tvOS
	$(MAKE) -C WebGL
	$(MAKE) -C Windows
	$(MAKE) -C Windows\ Phone
