LOCAL_PATH := $(call my-dir)/assimp-3.1.1

include $(CLEAR_VARS)

LOCAL_MODULE    := assimp

LOCAL_EXPORT_C_INCLUDES := \
$(LOCAL_PATH) \
$(MY_ASSIMP_PATH)/code \
$(MY_ASSIMP_PATH)/contrib/ConvertUTF/ \
$(MY_ASSIMP_PATH)/contrib/irrXML/ \
$(MY_ASSIMP_PATH)/contrib/poly2tri/poly2tri/common/ \
$(MY_ASSIMP_PATH)/contrib/poly2tri/poly2tri/ \
$(MY_ASSIMP_PATH)/contrib/poly2tri/poly2tri/sweep/ \
$(MY_ASSIMP_PATH)/contrib/unzip/ \
$(MY_ASSIMP_PATH)/include/ \
$(MY_ASSIMP_PATH)/contrib/clipper/ \
$(MY_ASSIMP_PATH)/code/BoostWorkaround/ \
$(MY_BULLET_PATH) \
$(MY_BULLET_PATH)/BulletCollision/BroadphaseCollision \
$(MY_BULLET_PATH)/BulletCollision/CollisionDispatch \
$(MY_BULLET_PATH)/BulletCollision/CollisionShapes \
$(MY_BULLET_PATH)/BulletCollision/Gimpact \
$(MY_BULLET_PATH)/BulletCollision/NarrowPhaseCollision \
$(MY_BULLET_PATH)/BulletDynamics/Character \
$(MY_BULLET_PATH)/BulletDynamics/ConstraintSolver \
$(MY_BULLET_PATH)/BulletDynamics/Dynamics \
$(MY_BULLET_PATH)/BulletDynamics/Featherstone \
$(MY_BULLET_PATH)/BulletDynamics/MLCPSolvers \
$(MY_BULLET_PATH)/BulletDynamics/Vehicle \
$(MY_BULLET_PATH)/BulletSoftBody \
$(MY_BULLET_PATH)/LinearMath \
$(MY_FMOD_PATH)/lowlevel/inc \
\
$(MY_JSON_PATH)/src/lib_json \
$(MY_JSON_PATH)/include \
$(MY_JSON_PATH)/src/test_lib_json \
$(MY_LUA_PATH) \
$(MY_NANOVG_PATH) \
$(MY_OGG_PATH) \
$(MY_OGG_PATH)/include \
$(MY_OGG_PATH)/include/ogg \
$(MY_OGG_PATH)/src \
$(MY_PLATFORM_PATH)/core \
$(MY_PLATFORM_PATH)/android \
$(MY_PNG_PATH) \
$(MY_SQLITE_PATH) \
$(MY_THEORA_PATH)/examples/ \
$(MY_THEORA_PATH)/include/ \
$(MY_THEORA_PATH)/lib/ \
$(MY_VORBIS_PATH)/ \
$(MY_VORBIS_PATH)/examples/ \
$(MY_VORBIS_PATH)/test \
$(MY_VORBIS_PATH)/include \
$(MY_VORBIS_PATH)/lib \
$(MY_XML_PATH) \
$(MY_ZLIB_PATH) \

LOCAL_CFLAGS := $(LOCAL_C_INCLUDES:%=-I%)

LOCAL_SRC_FILES := \
$(LOCAL_PATH)/contrib/ConvertUTF/ConvertUTF.c \
$(LOCAL_PATH)/contrib/unzip/ioapi.c \
$(LOCAL_PATH)/contrib/unzip/unzip.c \
$(LOCAL_PATH)/test/unit/CCompilerTest.c \
$(LOCAL_PATH)/code/3DSConverter.cpp \
$(LOCAL_PATH)/code/3DSLoader.cpp \
$(LOCAL_PATH)/code/ACLoader.cpp \
$(LOCAL_PATH)/code/ASELoader.cpp \
$(LOCAL_PATH)/code/ASEParser.cpp \
$(LOCAL_PATH)/code/Assimp.cpp \
$(LOCAL_PATH)/code/AssimpCExport.cpp \
$(LOCAL_PATH)/code/AssimpPCH.cpp \
$(LOCAL_PATH)/code/B3DImporter.cpp \
$(LOCAL_PATH)/code/BaseImporter.cpp \
$(LOCAL_PATH)/code/BaseProcess.cpp \
$(LOCAL_PATH)/code/Bitmap.cpp \
$(LOCAL_PATH)/code/BlenderBMesh.cpp \
$(LOCAL_PATH)/code/BlenderDNA.cpp \
$(LOCAL_PATH)/code/BlenderLoader.cpp \
$(LOCAL_PATH)/code/BlenderModifier.cpp \
$(LOCAL_PATH)/code/BlenderScene.cpp \
$(LOCAL_PATH)/code/BlenderTessellator.cpp \
$(LOCAL_PATH)/code/BVHLoader.cpp \
$(LOCAL_PATH)/code/CalcTangentsProcess.cpp \
$(LOCAL_PATH)/code/COBLoader.cpp \
$(LOCAL_PATH)/code/ColladaExporter.cpp \
$(LOCAL_PATH)/code/ColladaLoader.cpp \
$(LOCAL_PATH)/code/ColladaParser.cpp \
$(LOCAL_PATH)/code/ComputeUVMappingProcess.cpp \
$(LOCAL_PATH)/code/ConvertToLHProcess.cpp \
$(LOCAL_PATH)/code/CSMLoader.cpp \
$(LOCAL_PATH)/code/DeboneProcess.cpp \
$(LOCAL_PATH)/code/DefaultIOStream.cpp \
$(LOCAL_PATH)/code/DefaultIOSystem.cpp \
$(LOCAL_PATH)/code/DefaultLogger.cpp \
$(LOCAL_PATH)/code/DXFLoader.cpp \
$(LOCAL_PATH)/code/Exporter.cpp \
$(LOCAL_PATH)/code/FBXAnimation.cpp \
$(LOCAL_PATH)/code/FBXBinaryTokenizer.cpp \
$(LOCAL_PATH)/code/FBXConverter.cpp \
$(LOCAL_PATH)/code/FBXDeformer.cpp \
$(LOCAL_PATH)/code/FBXDocument.cpp \
$(LOCAL_PATH)/code/FBXDocumentUtil.cpp \
$(LOCAL_PATH)/code/FBXImporter.cpp \
$(LOCAL_PATH)/code/FBXMaterial.cpp \
$(LOCAL_PATH)/code/FBXMeshGeometry.cpp \
$(LOCAL_PATH)/code/FBXModel.cpp \
$(LOCAL_PATH)/code/FBXNodeAttribute.cpp \
$(LOCAL_PATH)/code/FBXParser.cpp \
$(LOCAL_PATH)/code/FBXProperties.cpp \
$(LOCAL_PATH)/code/FBXTokenizer.cpp \
$(LOCAL_PATH)/code/FBXUtil.cpp \
$(LOCAL_PATH)/code/FindDegenerates.cpp \
$(LOCAL_PATH)/code/FindInstancesProcess.cpp \
$(LOCAL_PATH)/code/FindInvalidDataProcess.cpp \
$(LOCAL_PATH)/code/FixNormalsStep.cpp \
$(LOCAL_PATH)/code/GenFaceNormalsProcess.cpp \
$(LOCAL_PATH)/code/GenVertexNormalsProcess.cpp \
$(LOCAL_PATH)/code/HMPLoader.cpp \
$(LOCAL_PATH)/code/IFCBoolean.cpp \
$(LOCAL_PATH)/code/IFCCurve.cpp \
$(LOCAL_PATH)/code/IFCGeometry.cpp \
$(LOCAL_PATH)/code/IFCLoader.cpp \
$(LOCAL_PATH)/code/IFCMaterial.cpp \
$(LOCAL_PATH)/code/IFCOpenings.cpp \
$(LOCAL_PATH)/code/IFCProfile.cpp \
$(LOCAL_PATH)/code/IFCReaderGen.cpp \
$(LOCAL_PATH)/code/IFCUtil.cpp \
$(LOCAL_PATH)/code/Importer.cpp \
$(LOCAL_PATH)/code/ImporterRegistry.cpp \
$(LOCAL_PATH)/code/ImproveCacheLocality.cpp \
$(LOCAL_PATH)/code/IRRLoader.cpp \
$(LOCAL_PATH)/code/IRRMeshLoader.cpp \
$(LOCAL_PATH)/code/IRRShared.cpp \
$(LOCAL_PATH)/code/JoinVerticesProcess.cpp \
$(LOCAL_PATH)/code/LimitBoneWeightsProcess.cpp \
$(LOCAL_PATH)/code/LWOAnimation.cpp \
$(LOCAL_PATH)/code/LWOBLoader.cpp \
$(LOCAL_PATH)/code/LWOLoader.cpp \
$(LOCAL_PATH)/code/LWOMaterial.cpp \
$(LOCAL_PATH)/code/LWSLoader.cpp \
$(LOCAL_PATH)/code/MakeVerboseFormat.cpp \
$(LOCAL_PATH)/code/MaterialSystem.cpp \
$(LOCAL_PATH)/code/MD2Loader.cpp \
$(LOCAL_PATH)/code/MD3Loader.cpp \
$(LOCAL_PATH)/code/MD5Loader.cpp \
$(LOCAL_PATH)/code/MD5Parser.cpp \
$(LOCAL_PATH)/code/MDCLoader.cpp \
$(LOCAL_PATH)/code/MDLLoader.cpp \
$(LOCAL_PATH)/code/MDLMaterialLoader.cpp \
$(LOCAL_PATH)/code/MS3DLoader.cpp \
$(LOCAL_PATH)/code/NDOLoader.cpp \
$(LOCAL_PATH)/code/NFFLoader.cpp \
$(LOCAL_PATH)/code/ObjExporter.cpp \
$(LOCAL_PATH)/code/ObjFileImporter.cpp \
$(LOCAL_PATH)/code/ObjFileMtlImporter.cpp \
$(LOCAL_PATH)/code/ObjFileParser.cpp \
$(LOCAL_PATH)/code/OFFLoader.cpp \
$(LOCAL_PATH)/code/OgreBinarySerializer.cpp \
$(LOCAL_PATH)/code/OgreImporter.cpp \
$(LOCAL_PATH)/code/OgreMaterial.cpp \
$(LOCAL_PATH)/code/OgreStructs.cpp \
$(LOCAL_PATH)/code/OgreXmlSerializer.cpp \
$(LOCAL_PATH)/code/OptimizeGraph.cpp \
$(LOCAL_PATH)/code/OptimizeMeshes.cpp \
$(LOCAL_PATH)/code/PlyExporter.cpp \
$(LOCAL_PATH)/code/PlyLoader.cpp \
$(LOCAL_PATH)/code/PlyParser.cpp \
$(LOCAL_PATH)/code/PostStepRegistry.cpp \
$(LOCAL_PATH)/code/PretransformVertices.cpp \
$(LOCAL_PATH)/code/ProcessHelper.cpp \
$(LOCAL_PATH)/code/Q3BSPFileImporter.cpp \
$(LOCAL_PATH)/code/Q3BSPFileParser.cpp \
$(LOCAL_PATH)/code/Q3BSPZipArchive.cpp \
$(LOCAL_PATH)/code/Q3DLoader.cpp \
$(LOCAL_PATH)/code/RawLoader.cpp \
$(LOCAL_PATH)/code/RemoveComments.cpp \
$(LOCAL_PATH)/code/RemoveRedundantMaterials.cpp \
$(LOCAL_PATH)/code/RemoveVCProcess.cpp \
$(LOCAL_PATH)/code/SceneCombiner.cpp \
$(LOCAL_PATH)/code/ScenePreprocessor.cpp \
$(LOCAL_PATH)/code/SGSpatialSort.cpp \
$(LOCAL_PATH)/code/SkeletonMeshBuilder.cpp \
$(LOCAL_PATH)/code/SMDLoader.cpp \
$(LOCAL_PATH)/code/SortByPTypeProcess.cpp \
$(LOCAL_PATH)/code/SpatialSort.cpp \
$(LOCAL_PATH)/code/SplitByBoneCountProcess.cpp \
$(LOCAL_PATH)/code/SplitLargeMeshes.cpp \
$(LOCAL_PATH)/code/StandardShapes.cpp \
$(LOCAL_PATH)/code/STEPFileEncoding.cpp \
$(LOCAL_PATH)/code/STEPFileReader.cpp \
$(LOCAL_PATH)/code/STLExporter.cpp \
$(LOCAL_PATH)/code/STLLoader.cpp \
$(LOCAL_PATH)/code/Subdivision.cpp \
$(LOCAL_PATH)/code/TargetAnimation.cpp \
$(LOCAL_PATH)/code/TerragenLoader.cpp \
$(LOCAL_PATH)/code/TextureTransform.cpp \
$(LOCAL_PATH)/code/TriangulateProcess.cpp \
$(LOCAL_PATH)/code/UnrealLoader.cpp \
$(LOCAL_PATH)/code/ValidateDataStructure.cpp \
$(LOCAL_PATH)/code/VertexTriangleAdjacency.cpp \
$(LOCAL_PATH)/code/XFileImporter.cpp \
$(LOCAL_PATH)/code/XFileParser.cpp \
$(LOCAL_PATH)/code/XGLLoader.cpp \
$(LOCAL_PATH)/contrib/clipper/clipper.cpp \
$(LOCAL_PATH)/contrib/irrXML/irrXML.cpp \
$(LOCAL_PATH)/contrib/poly2tri/poly2tri/common/shapes.cc \
$(LOCAL_PATH)/contrib/poly2tri/poly2tri/sweep/advancing_front.cc \
$(LOCAL_PATH)/contrib/poly2tri/poly2tri/sweep/cdt.cc \
$(LOCAL_PATH)/contrib/poly2tri/poly2tri/sweep/sweep.cc \
$(LOCAL_PATH)/contrib/poly2tri/poly2tri/sweep/sweep_context.cc \
#\
$(LOCAL_PATH)/samples/SimpleTexturedOpenGL/SimpleTexturedOpenGL/src/model_loading.cpp \
$(LOCAL_PATH)/test/unit/BoostWorkaround/tupletest.cpp \
$(LOCAL_PATH)/test/unit/Main.cpp \
$(LOCAL_PATH)/test/unit/UnitTestPCH.cpp \
$(LOCAL_PATH)/test/unit/utExport.cpp \
$(LOCAL_PATH)/test/unit/utFindDegenerates.cpp \
$(LOCAL_PATH)/test/unit/utFindInvalidData.cpp \
$(LOCAL_PATH)/test/unit/utFixInfacingNormals.cpp \
$(LOCAL_PATH)/test/unit/utGenNormals.cpp \
$(LOCAL_PATH)/test/unit/utImporter.cpp \
$(LOCAL_PATH)/test/unit/utImproveCacheLocality.cpp \
$(LOCAL_PATH)/test/unit/utJoinVertices.cpp \
$(LOCAL_PATH)/test/unit/utLimitBoneWeights.cpp \
$(LOCAL_PATH)/test/unit/utMaterialSystem.cpp \
$(LOCAL_PATH)/test/unit/utNoBoostTest.cpp \
$(LOCAL_PATH)/test/unit/utPretransformVertices.cpp \
$(LOCAL_PATH)/test/unit/utRemoveComments.cpp \
$(LOCAL_PATH)/test/unit/utRemoveComponent.cpp \
$(LOCAL_PATH)/test/unit/utRemoveRedundantMaterials.cpp \
$(LOCAL_PATH)/test/unit/utScenePreprocessor.cpp \
$(LOCAL_PATH)/test/unit/utSharedPPData.cpp \
$(LOCAL_PATH)/test/unit/utSortByPType.cpp \
$(LOCAL_PATH)/test/unit/utSplitLargeMeshes.cpp \
$(LOCAL_PATH)/test/unit/utTargetAnimation.cpp \
$(LOCAL_PATH)/test/unit/utTextureTransform.cpp \
$(LOCAL_PATH)/test/unit/utTriangulate.cpp \
$(LOCAL_PATH)/test/unit/utVertexTriangleAdjacency.cpp \
$(LOCAL_PATH)/tools/assimp_cmd/CompareDump.cpp \
$(LOCAL_PATH)/tools/assimp_cmd/Export.cpp \
$(LOCAL_PATH)/tools/assimp_cmd/ImageExtractor.cpp \
$(LOCAL_PATH)/tools/assimp_cmd/Info.cpp \
$(LOCAL_PATH)/tools/assimp_cmd/Main.cpp \
$(LOCAL_PATH)/tools/assimp_cmd/WriteDumb.cpp \
$(LOCAL_PATH)/tools/assimp_view/AnimEvaluator.cpp \
$(LOCAL_PATH)/tools/assimp_view/assimp_view.cpp \
$(LOCAL_PATH)/tools/assimp_view/Background.cpp \
$(LOCAL_PATH)/tools/assimp_view/Display.cpp \
$(LOCAL_PATH)/tools/assimp_view/HelpDialog.cpp \
$(LOCAL_PATH)/tools/assimp_view/Input.cpp \
$(LOCAL_PATH)/tools/assimp_view/LogDisplay.cpp \
$(LOCAL_PATH)/tools/assimp_view/LogWindow.cpp \
$(LOCAL_PATH)/tools/assimp_view/Material.cpp \
$(LOCAL_PATH)/tools/assimp_view/MeshRenderer.cpp \
$(LOCAL_PATH)/tools/assimp_view/MessageProc.cpp \
$(LOCAL_PATH)/tools/assimp_view/Normals.cpp \
$(LOCAL_PATH)/tools/assimp_view/SceneAnimator.cpp \
$(LOCAL_PATH)/tools/assimp_view/Shaders.cpp \
$(LOCAL_PATH)/tools/assimp_view/stdafx.cpp \
#\
$(LOCAL_PATH)/CMakeFiles/CheckTypeSize/OFF64_T.c \
$(LOCAL_PATH)/samples/SimpleOpenGL/Sample_SimpleOpenGL.c \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/AdditionalMessage.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/Asserter.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/BeOsDynamicLibraryManager.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/BriefTestProgressListener.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/CompilerOutputter.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/DefaultProtector.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/DllMain.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/DynamicLibraryManager.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/DynamicLibraryManagerException.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/Exception.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/Message.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/PlugInManager.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/PlugInParameters.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/Protector.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/ProtectorChain.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/RepeatedTest.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/ShlDynamicLibraryManager.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/SourceLine.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/StringTools.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/SynchronizedObject.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/Test.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestAssert.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestCase.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestCaseDecorator.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestComposite.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestDecorator.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestFactoryRegistry.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestFailure.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestLeaf.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestNamer.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestPath.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestPlugInDefaultImpl.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestResult.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestResultCollector.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestRunner.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestSetUp.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestSuccessListener.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestSuite.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TestSuiteBuilderContext.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TextOutputter.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TextTestProgressListener.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TextTestResult.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TextTestRunner.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/TypeInfoHelper.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/UnixDynamicLibraryManager.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/Win32DynamicLibraryManager.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/XmlDocument.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/XmlElement.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/XmlOutputter.cpp \
$(LOCAL_PATH)/contrib/cppunit-1.12.1/src/cppunit/XmlOutputterHook.cpp \
$(LOCAL_PATH)/port/jassimp/jassimp-native/src/jassimp.cpp \
\
$(LOCAL_PATH)/contrib/zlib/adler32.c \
$(LOCAL_PATH)/contrib/zlib/compress.c \
$(LOCAL_PATH)/contrib/zlib/crc32.c \
$(LOCAL_PATH)/contrib/zlib/deflate.c \
$(LOCAL_PATH)/contrib/zlib/gzclose.c \
$(LOCAL_PATH)/contrib/zlib/gzlib.c \
$(LOCAL_PATH)/contrib/zlib/gzread.c \
$(LOCAL_PATH)/contrib/zlib/gzwrite.c \
$(LOCAL_PATH)/contrib/zlib/infback.c \
$(LOCAL_PATH)/contrib/zlib/inffast.c \
$(LOCAL_PATH)/contrib/zlib/inflate.c \
$(LOCAL_PATH)/contrib/zlib/inftrees.c \
$(LOCAL_PATH)/contrib/zlib/trees.c \
$(LOCAL_PATH)/contrib/zlib/uncompr.c \
$(LOCAL_PATH)/contrib/zlib/zutil.c \

include $(BUILD_STATIC_LIBRARY)
